{
  "openapi": "3.0.1",
  "info": {
    "title": "Socbay API",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [],
  "paths": {
    "/user/setOTP": {
      "post": {
        "summary": "setOTP",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "phone": {
                    "type": "string"
                  }
                },
                "required": [
                  "phone"
                ]
              },
              "example": {
                "phone": ""
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/user/checkOTP": {
      "post": {
        "summary": "checkOTP",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "phone": {
                    "type": "string"
                  }
                },
                "required": [
                  "phone"
                ]
              },
              "example": {
                "phone": ""
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/user/support": {
      "get": {
        "summary": "supportPhone",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/user/register": {
      "post": {
        "summary": "register",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "phone": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "pass": {
                    "type": "string"
                  }
                },
                "required": [
                  "phone",
                  "name",
                  "pass"
                ]
              },
              "example": {
                "phone": "0392808871",
                "name": "DQHoang",
                "pass": "123456"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/user/updateUser": {
      "post": {
        "summary": "updateUser",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "phone": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  },
                  "password_confirmation": {
                    "type": "string"
                  },
                  "address": {
                    "type": "string"
                  }
                },
                "required": [
                  "phone",
                  "password",
                  "password_confirmation",
                  "address"
                ]
              },
              "example": {
                "phone": "0392808871",
                "password": "123456",
                "password_confirmation": "123456",
                "address": "Hanoi"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/user/login": {
      "post": {
        "summary": "login",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "phone": {
                    "type": "string"
                  },
                  "pass": {
                    "type": "string"
                  }
                },
                "required": [
                  "phone",
                  "pass"
                ]
              },
              "example": {
                "phone": "0943498335",
                "pass": "hoang123"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/user/check": {
      "post": {
        "summary": "checkUser",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "phone": {
                    "type": "string"
                  }
                },
                "required": [
                  "phone"
                ]
              },
              "example": {
                "phone": "0392808871"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/user/listProduct/{user_id}": {
      "get": {
        "summary": "listProduct",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/user/history/{id}": {
      "get": {
        "summary": "history",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/user/detailHistory/{order_id}": {
      "get": {
        "summary": "detailHistory",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/user/listUserByService": {
      "get": {
        "summary": "listUserByService",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/user/user_list/{page}": {
      "get": {
        "summary": "userList",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/user/searchUser_list": {
      "get": {
        "summary": "searchUserList",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/user/rate/{userid}/{order_id}": {
      "post": {
        "summary": "rate",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              },
              "example": {}
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/user/addFavorite": {
      "post": {
        "summary": "addFavorite",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "user_id": {
                    "type": "string"
                  },
                  "staff_id": {
                    "type": "string"
                  }
                },
                "required": [
                  "user_id",
                  "staff_id"
                ]
              },
              "example": {
                "user_id": "",
                "staff_id": ""
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/user/unFavorite": {
      "post": {
        "summary": "unFavorite",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "user_id": {
                    "type": "string"
                  },
                  "staff_id": {
                    "type": "string"
                  }
                },
                "required": [
                  "user_id",
                  "staff_id"
                ]
              },
              "example": {
                "user_id": "",
                "staff_id": ""
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/user/{id}": {
      "get": {
        "summary": "getUser",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "example": "8968",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/user/staff-detail/{id}": {
      "get": {
        "summary": "staffDetail",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/user/1234567888/changePassWord": {
      "post": {
        "summary": "changePassword",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "password": {
                    "type": "string"
                  },
                  "new_password": {
                    "type": "string"
                  },
                  "new_password_confirm": {
                    "type": "string"
                  }
                },
                "required": [
                  "password",
                  "new_password",
                  "new_password_confirm"
                ]
              },
              "example": {
                "password": "",
                "new_password": "admin999",
                "new_password_confirm": "admin999"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/blog/search": {
      "get": {
        "summary": "search",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/blog/list": {
      "get": {
        "summary": "list",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/blog/{id}": {
      "get": {
        "summary": "blog",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/blog/listPhilanthropy": {
      "get": {
        "summary": "charity",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/service/listService": {
      "get": {
        "summary": "listService",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/service/{id}": {
      "get": {
        "summary": "serviceID",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/notify/sendTopic": {
      "get": {
        "summary": "sendPushNoti",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/notify/list": {
      "get": {
        "summary": "notify-list",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/notify/{id}": {
      "get": {
        "summary": "notifyID",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/product/search": {
      "get": {
        "summary": "search",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/product/listCate": {
      "get": {
        "summary": "listCategory",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/product/list": {
      "get": {
        "summary": "listProduct",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/product/{id]": {
      "get": {
        "summary": "productID",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/tasks": {
      "get": {
        "summary": "index",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/tasks/ton-dong": {
      "get": {
        "summary": "backlog",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/tasks/{id}": {
      "get": {
        "summary": "tasksID",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/tasks/edit/{id}": {
      "post": {
        "summary": "editSale",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/tasks/editt/{id}": {
      "post": {
        "summary": "editStaff",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/tasks/them": {
      "post": {
        "summary": "them",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "customer": {
                    "type": "string"
                  }
                },
                "required": [
                  "customer"
                ]
              },
              "example": ""
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/tasks/xoa": {
      "post": {
        "summary": "xoa",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/tasks/phone": {
      "post": {
        "summary": "phone",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "phone": {
                    "type": "string"
                  }
                },
                "required": [
                  "phone"
                ]
              },
              "example": {
                "phone": "0392808871"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/tasks/customer/2627": {
      "get": {
        "summary": "tasksByCustomer",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/order/get-product-by-user/6206": {
      "get": {
        "summary": "getProductByUser",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/order/phone": {
      "post": {
        "summary": "phone",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "phone": {
                    "type": "string"
                  }
                },
                "required": [
                  "phone"
                ]
              },
              "example": {
                "phone": "0392808871"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/order/upload-image": {
      "post": {
        "summary": "uploadImage",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "image_link": {
                    "type": "string"
                  }
                },
                "required": [
                  "image_link"
                ]
              },
              "example": {
                "image_link": ""
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/order/save-repair": {
      "post": {
        "summary": "save-repair",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "product_id": {
                    "type": "string"
                  },
                  "user_id": {
                    "type": "integer"
                  },
                  "replaceDate": {
                    "type": "string"
                  },
                  "replaceDatePromise": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "corePrice": {
                    "type": "integer"
                  },
                  "listCores": {
                    "type": "integer"
                  },
                  "chiet_khau": {
                    "type": "integer"
                  },
                  "status": {
                    "type": "integer"
                  },
                  "tich_diem": {
                    "type": "integer"
                  },
                  "tru_diem": {
                    "type": "integer"
                  },
                  "sale_id": {
                    "type": "integer"
                  },
                  "type_payment": {
                    "type": "integer"
                  },
                  "image_link": {
                    "type": "string"
                  },
                  "address": {
                    "type": "string"
                  }
                },
                "required": [
                  "product_id",
                  "user_id",
                  "replaceDate",
                  "replaceDatePromise",
                  "name",
                  "corePrice",
                  "listCores",
                  "chiet_khau",
                  "status",
                  "tich_diem",
                  "tru_diem",
                  "sale_id",
                  "type_payment",
                  "image_link",
                  "address"
                ]
              },
              "example": {
                "product_id": "143",
                "user_id": 6206,
                "replaceDate": "2024-04-09",
                "replaceDatePromise": "2024-05-01",
                "name": "Core 2",
                "corePrice": 100000,
                "listCores": 0,
                "chiet_khau": 10,
                "status": 2,
                "tich_diem": 100,
                "tru_diem": 20,
                "sale_id": 161,
                "type_payment": 1,
                "image_link": "/product_images/bo-3-loi-loc-nuoc-karofi-123-237.jpg",
                "address": "User's Address"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/order/filterCore/{id}": {
      "get": {
        "summary": "filterCore",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/order/them": {
      "post": {
        "summary": "add-order",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "user_id": {
                    "type": "integer"
                  },
                  "listProducts": {
                    "type": "integer"
                  },
                  "price": {
                    "type": "integer"
                  },
                  "ngaymua": {
                    "type": "string"
                  },
                  "count": {
                    "type": "integer"
                  },
                  "socaploc": {
                    "type": "integer"
                  },
                  "address": {
                    "type": "string"
                  },
                  "chiet_khau": {
                    "type": "integer"
                  },
                  "status": {
                    "type": "integer"
                  },
                  "tich_diem": {
                    "type": "integer"
                  },
                  "tru_diem": {
                    "type": "integer"
                  },
                  "type": {
                    "type": "integer"
                  },
                  "origin": {
                    "type": "integer"
                  },
                  "sale_id": {
                    "type": "integer"
                  },
                  "type_payment": {
                    "type": "integer"
                  },
                  "staff": {
                    "type": "integer"
                  }
                },
                "required": [
                  "user_id",
                  "listProducts",
                  "price",
                  "ngaymua",
                  "count",
                  "socaploc",
                  "address",
                  "chiet_khau",
                  "status",
                  "tich_diem",
                  "tru_diem",
                  "type",
                  "origin",
                  "sale_id",
                  "type_payment",
                  "staff"
                ]
              },
              "example": {
                "user_id": 6206,
                "listProducts": 154,
                "price": 1000,
                "ngaymua": "2024-04-05",
                "count": 2,
                "socaploc": 1,
                "address": "Address 2",
                "chiet_khau": 10,
                "status": 2,
                "tich_diem": 50,
                "tru_diem": 0,
                "type": 1,
                "origin": 2,
                "sale_id": 161,
                "type_payment": 1,
                "staff": 2
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/fcm": {
      "post": {
        "summary": "saveFCMToken",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "user_id": {
                    "type": "string"
                  },
                  "fcm_token": {
                    "type": "string"
                  }
                },
                "required": [
                  "user_id",
                  "fcm_token"
                ]
              },
              "example": {
                "user_id": "",
                "fcm_token": ""
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    },
    "/districts": {
      "get": {
        "summary": "districts",
        "deprecated": false,
        "description": "",
        "tags": [],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "security": []
      }
    }
  },
  "components": {
    "schemas": {},
    "responses": {
      "BadRequest": {
        "description": "",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "example": "https://example.com/errors/bad-request"
                },
                "title": {
                  "type": "string",
                  "example": "Bad Request"
                },
                "status": {
                  "type": "integer",
                  "example": 400
                },
                "detail": {
                  "type": "string",
                  "example": "The request is invalid or missing required parameters."
                }
              }
            },
            "examples": {
              "Example": {
                "summary": "Example",
                "value": {
                  "type": "https://example.com/errors/bad-request",
                  "title": "Bad Request",
                  "status": 400,
                  "detail": "The request is invalid or missing required parameters."
                }
              }
            }
          }
        }
      },
      "Unauthorized": {
        "description": "",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "example": "https://example.com/errors/unauthorized"
                },
                "title": {
                  "type": "string",
                  "example": "Unauthorized"
                },
                "status": {
                  "type": "integer",
                  "example": 401
                },
                "detail": {
                  "type": "string",
                  "example": "You do not have the necessary permissions."
                }
              }
            },
            "examples": {
              "Example": {
                "summary": "Example",
                "value": {
                  "type": "https://example.com/errors/unauthorized",
                  "title": "Unauthorized",
                  "status": 401,
                  "detail": "You do not have the necessary permissions."
                }
              }
            }
          }
        }
      },
      "Forbidden": {
        "description": "",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "example": "https://example.com/errors/forbidden"
                },
                "title": {
                  "type": "string",
                  "example": "Forbidden"
                },
                "status": {
                  "type": "integer",
                  "example": 403
                },
                "detail": {
                  "type": "string",
                  "example": "Access is forbidden with the provided credentials."
                }
              }
            },
            "examples": {
              "Example": {
                "summary": "Example",
                "value": {
                  "type": "https://example.com/errors/forbidden",
                  "title": "Forbidden",
                  "status": 403,
                  "detail": "Access is forbidden with the provided credentials."
                }
              }
            }
          }
        }
      },
      "NotFound": {
        "description": "",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "example": "https://example.com/errors/not-found"
                },
                "title": {
                  "type": "string",
                  "example": "Not Found"
                },
                "status": {
                  "type": "integer",
                  "example": 404
                },
                "detail": {
                  "type": "string",
                  "example": "The specified resource does not exist."
                }
              }
            },
            "examples": {
              "Example": {
                "summary": "Example",
                "value": {
                  "type": "https://example.com/errors/not-found",
                  "title": "Not Found",
                  "status": 404,
                  "detail": "The specified resource does not exist."
                }
              }
            }
          }
        }
      },
      "TooManyRequests": {
        "description": "",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "example": "https://example.com/errors/too-many-requests"
                },
                "title": {
                  "type": "string",
                  "example": "Too Many Requests"
                },
                "status": {
                  "type": "integer",
                  "example": 429
                },
                "detail": {
                  "type": "string",
                  "example": "You have exceeded the rate limit."
                }
              }
            },
            "examples": {
              "Example": {
                "summary": "Example",
                "value": {
                  "type": "https://example.com/errors/too-many-requests",
                  "title": "Too Many Requests",
                  "status": 429,
                  "detail": "You have exceeded the rate limit."
                }
              }
            }
          }
        }
      },
      "InternalServerError": {
        "description": "",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "example": "https://example.com/errors/internal-server-error"
                },
                "title": {
                  "type": "string",
                  "example": "Internal Server Error"
                },
                "status": {
                  "type": "integer",
                  "example": 500
                },
                "detail": {
                  "type": "string",
                  "example": "An unexpected error occurred."
                }
              }
            },
            "examples": {
              "Example": {
                "summary": "Example",
                "value": {
                  "type": "https://example.com/errors/internal-server-error",
                  "title": "Internal Server Error",
                  "status": 500,
                  "detail": "An unexpected error occurred."
                }
              }
            }
          }
        }
      }
    },
    "securitySchemes": {}
  },
  "servers": [],
  "security": []
}